#!/usr/bin/env bash
# Merge the next upstream commit into main, one commit per merge commit
# (see docs/upgrade_from_upstream_guide.md and CLAUDE.md — never merge a range).
#
# Deterministic conflict resolutions are applied automatically:
#   Scenario A: re-introduced translations/deskflow_*.ts        -> git rm
#   Scenario J: re-introduced .github/                          -> git rm
#   Scenario L: conflicts under src/unittests/                  -> take upstream
#   Scenario B: new icons under icons/deskflow-light/           -> move to dshare-hid-light/
# Everything else stops the script for human resolution (Scenarios C-M).
#
# Usage:
#   merge_next_upstream.sh          # merge exactly one commit
#   merge_next_upstream.sh --all    # loop until backlog empty or human needed
#
# Exit codes: 0 = merged (or already up to date), 2 = conflicts need a human.
set -uo pipefail

cd "$(git rev-parse --show-toplevel)"

if [ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]; then
  echo "ERROR: run on main (currently on $(git rev-parse --abbrev-ref HEAD))" >&2
  exit 1
fi
if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: worktree not clean; commit or stash first" >&2
  exit 1
fi

git fetch upstream

merge_one() {
  local next subject body short applied
  next=$(git log --reverse --format=%H main..upstream/master | head -1)
  if [ -z "$next" ]; then
    echo "Up to date with upstream/master."
    return 10
  fi
  subject=$(git log -1 --format=%s "$next")
  body=$(git log -1 --format=%b "$next")
  short=$(git rev-parse --short=10 "$next")
  echo "=== Merging $short: $subject"

  git merge --no-ff --no-commit "$next" >/dev/null 2>&1
  applied=""

  # Scenario A: upstream translations are regenerated by lupdate; discard.
  if git status --porcelain | grep -qE 'translations/deskflow_.*\.ts'; then
    git rm -f --ignore-unmatch 'translations/deskflow_*.ts' >/dev/null
    applied="$applied Scenario A: dropped re-introduced deskflow_*.ts."
  fi

  # Scenario J: this fork does not use upstream CI/workflows.
  if [ -e .github ] || git status --porcelain | grep -q '\.github/'; then
    git rm -rf --ignore-unmatch .github >/dev/null 2>&1
    rm -rf .github
    applied="$applied Scenario J: dropped re-introduced .github."
  fi

  # Scenario L: unittests are never compiled (BUILD_TESTS=OFF); take upstream.
  if git diff --name-only --diff-filter=U | grep -q '^src/unittests/'; then
    git diff --name-only --diff-filter=U | grep '^src/unittests/' | while read -r f; do
      git checkout --theirs -- "$f" 2>/dev/null || git rm -f -- "$f" >/dev/null
      git add -- "$f" 2>/dev/null
    done
    applied="$applied Scenario L: took upstream src/unittests."
  fi

  # Scenario B: new upstream icons belong in the rebranded theme directory.
  if [ -d src/apps/res/icons/deskflow-light ]; then
    (cd src/apps/res/icons/deskflow-light && find . -type f) | while read -r f; do
      mkdir -p "src/apps/res/icons/dshare-hid-light/$(dirname "$f")"
      git mv -f "src/apps/res/icons/deskflow-light/$f" \
                "src/apps/res/icons/dshare-hid-light/$f" 2>/dev/null
    done
    rm -rf src/apps/res/icons/deskflow-light
    applied="$applied Scenario B: moved new icons into dshare-hid-light."
  fi

  # Anything still conflicted needs a human (Scenarios C-M).
  local unresolved
  unresolved=$(git diff --name-only --diff-filter=U)
  if [ -n "$unresolved" ]; then
    echo "--- HUMAN NEEDED: unresolved conflicts (resolve per Scenarios C-M):"
    echo "$unresolved" | sed 's/^/    /'
    printf '%s\n\n%s\n\nMerged from upstream %s.%s\n' \
      "$subject" "$body" "$short" "$applied" > .git/MERGE_MSG_TEMPLATE
    echo "--- After resolving: git commit -F .git/MERGE_MSG_TEMPLATE (append scenario notes)"
    return 2
  fi

  # Rebrand watch: warn (never auto-edit) if the merge introduces identity strings.
  local warn
  warn=$(git diff --cached | grep -E '^\+' | grep -nE 'Deskflow|deskflow\.org|io\.github\.deskflow' \
        | grep -vE 'deskflow::|DeskflowException|deskflow/|mouse and keyboard sharing|SPDX' | head -5)
  [ -n "$warn" ] && echo "--- REBRAND WATCH (review these added lines):" && echo "$warn" | sed 's/^/    /'

  printf '%s\n\n%s\n\nMerged from upstream %s.%s\n' \
    "$subject" "$body" "$short" "$applied" | git commit -q -F -
  echo "=== Committed merge of $short"
  return 0
}

if [ "${1:-}" = "--all" ]; then
  while merge_one; do :; done
  rc=$?
  [ "$rc" = 10 ] && exit 0 || exit "$rc"
else
  merge_one
  rc=$?
  [ "$rc" = 10 ] && exit 0 || exit "$rc"
fi
